ZooPlanet/ZooPlanet.Web/Areas/Admin/Controllers/ContactsController.cs
namespace ZooPlanet.Web.Areas.Admin.Controllers
{
    using ZooPlanet.Common.Constants;
    using ZooPlanet.Data.Models.Enums;
    using ZooPlanet.Services.Admin;
    using ZooPlanet.Web.Areas.Admin.Models.Contacts;
    using ZooPlanet.Web.Controllers;
    using ZooPlanet.Web.Infrastructure.Extensions;
    using ZooPlanet.Web.Infrastructure.Filters;

    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Threading.Tasks;

    public class ContactsController : BaseAdminController
    {
        private readonly IContactAdminService contacts;

        public ContactsController(IContactAdminService contacts)
        {
            this.contacts = contacts;
        }

        [HttpGet]
        public async Task<IActionResult> All(int id = 1, ContactFilter filter = ContactFilter.All)
        {
            var contacts = await this.contacts.AllAsync(id, filter);

            var contactsCount = await this.contacts.CountAsync();

            var model = new ContactsListingViewModel
            {
                Contacts = contacts,
                CurrentPage = id,
                ContactsCount = contactsCount,
                PagesCount = (int)Math.Ceiling(contactsCount / (decimal)WebConstants.ContactsPerPage)
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var contact = await this.contacts.ByIdAsync(id);

            if (contact == null)
            {
                return NotFound();
            }

            var model = new ContactAdminViewModel
            {
                Id = contact.Id,
                Title = contact.Title,
                Message = contact.Message,
                ContactType = contact.ContactType,
                IsAnswered = contact.IsAnswered
            };

            return View(model);
        }

        [HttpPost]
        [Log]
        public async Task<IActionResult> Edit(ContactAdminViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var contact = await this.contacts.ByIdAsync(model.Id);

            if (contact == null)
            {
                return NotFound();
            }

            await this.contacts.EditAsync(model.Id, model.Title, model.Message, model.ContactType, model.IsAnswered);

            TempData.AddSuccessMessage($"Successfully edited contact {contact.Title}.");

            return this.RedirectToCustomAction(
                nameof(HomeController.Index),
                nameof(HomeController),
                new { area = string.Empty });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var contact = await this.contacts.ByIdAsync(id);

            if (contact == null)
            {
                return NotFound();
            }

            var model = new DeleteContactViewModel
            {
                Id = id,
                Title = contact.Title
            };

            return View(model);
        }

        [HttpPost]
        [Log]
        public async Task<IActionResult> Destroy(int id)
        {
            var contact = await this.contacts.ByIdAsync(id);

            if (contact == null)
            {
                return NotFound();
            }

            await this.contacts.DeleteAsync(id);

            TempData.AddSuccessMessage("Successfully deleted a contact.");

            return this.RedirectToCustomAction(
               nameof(HomeController.Index),
               nameof(HomeController),
               new { area = string.Empty });
        }
    }
}

ZooPlanet/ZooPlanet.Web/Areas/Admin/Controllers/UsersController.cs
namespace ZooPlanet.Web.Areas.Admin.Controllers
{
    using ZooPlanet.Common.Constants;
    using ZooPlanet.Data.Models;
    using ZooPlanet.Services.Admin;
    using ZooPlanet.Web.Areas.Admin.Models.Users;
    using ZooPlanet.Web.Controllers;
    using ZooPlanet.Web.Infrastructure.Extensions;
    using ZooPlanet.Web.Infrastructure.Filters;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    public class UsersController : BaseAdminController
    {
        private readonly UserManager<User> userManager;
        private readonly IUserAdminService users;

        public UsersController(
            UserManager<User> userManager,
            IUserAdminService users)
        {
            this.userManager = userManager;
            this.users = users;
        }

        [HttpGet]
        public IActionResult Index() => View();

        [HttpGet]
        public IActionResult AddUserToRole() => View();

        [HttpPost]
        [Log]
        public async Task<IActionResult> AddUserToRole(UserRoleViewModel model)
        {
            var user = await this.users.GetUserByNameAsync(model.UserName);

            if (user == null)
            {
                TempData.AddErrorMessage($"User {user.UserName} could not be found.");
                return NotFound();
            }
            
            await this.userManager.AddToRoleAsync(user, WebConstants.ZooEmployeeRole);

            TempData.AddSuccessMessage($"User {user.UserName} successfully added to role '{WebConstants.ZooEmployeeRole}'.");

            return this.RedirectToCustomAction(
                nameof(HomeController.Index),
                nameof(HomeController),
                new { area = string.Empty });
        }

        [HttpGet]
        public IActionResult RemoveUserFromRole() => View();

        [HttpPost]
        [Log]
        public async Task<IActionResult> RemoveUserFromRole(UserRoleViewModel model)
        {
            var user = await this.users.GetUserByNameAsync(model.UserName);

            if (user == null)
            {
                TempData.AddErrorMessage($"User {user.UserName} could not be found.");
                return NotFound();
            }
            
            await this.userManager.RemoveFromRoleAsync(user, WebConstants.ZooEmployeeRole);

            TempData.AddSuccessMessage($"User {user.UserName} successfully removed from role '{WebConstants.ZooEmployeeRole}'.");

            return this.RedirectToCustomAction(
                nameof(HomeController.Index),
                nameof(HomeController),
                new { area = string.Empty });
        }
    }
}

ZooPlanet/ZooPlanet.Web/Controllers/AnimalsController.cs
namespace ZooPlanet.Web.Controllers
{
    using ZooPlanet.Common.Constants;
    using ZooPlanet.Data.Models;
    using ZooPlanet.Services;
    using ZooPlanet.Web.Infrastructure.Extensions;
    using ZooPlanet.Web.Infrastructure.Filters;
    using ZooPlanet.Web.Models.Animals;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Threading.Tasks;

    public class AnimalsController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IAnimalService animals;

        public AnimalsController(UserManager<User> userManager, IAnimalService animals)
        {
            this.userManager = userManager;
            this.animals = animals;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int id = 1)
        {
            var animals = await this.animals.AllAsync(id);

            var animalsCount = await this.animals.CountAsync();

            var model = new AnimalsListingViewModel
            {
                Animals = animals,
                CurrentPage = id,
                AnimalsCount = animalsCount,
                PagesCount = (int)Math.Ceiling(animalsCount / (decimal)WebConstants.AnimalsPerPage)
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Mammals() => View();

        [HttpGet]
        public IActionResult Reptiles() => View();

        [HttpGet]
        public IActionResult Birds() => View();

        [HttpGet]
        public IActionResult Amphibians() => View();

        [HttpGet]
        public IActionResult Arthropods() => View();

        [HttpGet]
        public IActionResult Fish() => View();

        [HttpGet]
        [Authorize(Roles = WebConstants.AdministratorRole + "," + WebConstants.ZooEmployeeRole)]
        public IActionResult Add() => View();

        [HttpPost]
        [Log]
        [Authorize(Roles = WebConstants.AdministratorRole + "," + WebConstants.ZooEmployeeRole)]
        public async Task<IActionResult> Add(AnimalFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await userManager.GetUserAsync(User);

            await this.animals
                .AddAsync(model.Name, model.Age, model.ImageUrl, model.AnimalClass, user.Id);
            
            TempData.AddSuccessMessage("Successfully added animal to zoo.");

            return this.RedirectToCustomAction(
                nameof(HomeController.Index),
                nameof(HomeController),
                new { area = string.Empty });
        }

        [HttpGet]
        [Authorize(Roles = WebConstants.ZooEmployeeRole + "," + WebConstants.AdministratorRole)]
        public async Task<IActionResult> Edit(int id)
        {
            var user = await this.userManager.GetUserAsync(User);

            var animal = await this.animals.ByUserAsync(id, user);

            var isInAdminRole = await this.userManager.IsInRoleAsync(user, WebConstants.AdministratorRole);

            if (isInAdminRole)
            {
                animal = await this.animals.ByIdAsync(id);
            }

            if (animal == null)
            {
                return this.AccessDenied();
            }

            var model = new AnimalFormViewModel
            {
                Name = animal.Name,
                Age = animal.Age,
                ImageUrl = animal.ImageUrl,
                AnimalClass = animal.AnimalClass,
            };

            return View(model);
        }

        [HttpPost]
        [Log]
        [Authorize(Roles = WebConstants.ZooEmployeeRole + "," + WebConstants.AdministratorRole)]
        public async Task<IActionResult> Edit(AnimalFormViewModel model)
        {
            var user = await this.userManager.GetUserAsync(User);

            var animal = await this.animals.ByUserAsync(model.Id, user);

            var isInAdminRole = await this.userManager.IsInRoleAsync(user, WebConstants.AdministratorRole);

            if (isInAdminRole)
            {
                animal = await this.animals.ByIdAsync(model.Id);
            }

            if (animal == null)
            {
                return this.AccessDenied();
            }
            
            await this.animals.EditAsync(
                animal.Id,
                model.Name,
                model.Age,
                model.AnimalClass,
                model.ImageUrl);

            TempData.AddSuccessMessage($"Successfully edited animal {animal.Name}.");

            return this.RedirectToCustomAction(
                nameof(HomeController.Index),
                nameof(HomeController),
                new { area = string.Empty });
        }

        [HttpGet]
        [Authorize(Roles = WebConstants.ZooEmployeeRole + "," + WebConstants.AdministratorRole)]
        public async Task<IActionResult> Delete(int id)
        {
            var user = await this.userManager.GetUserAsync(User);

            var animal = await this.animals.ByUserAsync(id, user);

            var isInAdminRole = await this.userManager.IsInRoleAsync(user, WebConstants.AdministratorRole);

            if (isInAdminRole)
            {
                animal = await this.animals.ByIdAsync(id);
            }

            if (animal == null)
            {
                return this.AccessDenied();
            }

            var model = new DeleteAnimalViewModel
            {
                Id = animal.Id,
                Name = animal.Name
            };

            return View(model);
        }

        [HttpPost]
        [Log]
        [Authorize(Roles = WebConstants.ZooEmployeeRole + "," + WebConstants.AdministratorRole)]
        public async Task<IActionResult> Destroy(int id)
        {
            var user = await this.userManager.GetUserAsync(User);

            var animal = await this.animals.ByUserAsync(id, user);

            var isInAdminRole = await this.userManager.IsInRoleAsync(user, WebConstants.AdministratorRole);

            if (isInAdminRole)
            {
                animal = await this.animals.ByIdAsync(id);
            }

            if (animal == null)
            {
                return this.AccessDenied();
            }

            await this.animals.DeleteAsync(id);

            TempData.AddSuccessMessage("Successfully deleted an animal.");

            return this.RedirectToCustomAction(
               nameof(HomeController.Index),
               nameof(HomeController),
               new { area = string.Empty });
        }
    }
}

ZooPlanet/ZooPlanet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Zoo Planet</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Duru+Sans|Actor' rel='stylesheet' type='text/css'>
    <link href="~/lib/bootstrap/dist/css/bootshape.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/custom-checkbox-radio.css" rel="stylesheet" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><span class="green">Zoo</span> Planet</a>
                </div>
                <nav role="navigation" class="collapse navbar-collapse navbar-right">
                    <ul class="navbar-nav nav">
                        <li class="active"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        @if (User.IsInRole(WebConstants.AdministratorRole))
                        {
                            <li class="dropdown">
                                <a data-toggle="dropdown" href="#" class="dropdown-toggle">Admin <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="Admin" asp-controller="Users" asp-action="AddUserToRole">Add user to role</a></li>
                                    <li><a asp-area="Admin" asp-controller="Users" asp-action="RemoveUserFromRole">Remove user from role</a></li>
                                    <li><a asp-area="Admin" asp-controller="Contacts" asp-action="All">Contacts</a></li>
                                </ul>
                            </li>
                        }
                        <li class="dropdown">
                            <a data-toggle="dropdown" href="#" class="dropdown-toggle">Animal Classes<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Animals" asp-action="Mammals">Mammals</a></li>
                                <li><a asp-area="" asp-controller="Animals" asp-action="Reptiles">Reptiles</a></li>
                                <li><a asp-area="" asp-controller="Animals" asp-action="Birds">Birds</a></li>
                                <li><a asp-area="" asp-controller="Animals" asp-action="Arthropods">Arthropods</a></li>
                                <li><a asp-area="" asp-controller="Animals" asp-action="Amphibians">Amphibians</a></li>
                                <li><a asp-area="" asp-controller="Animals" asp-action="Fish">Fish</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animals" asp-action="Index">Animals</a>
                        </li>
                        @if (User.IsInRole(WebConstants.AdministratorRole) || User.IsInRole(WebConstants.ZooEmployeeRole))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Animals" asp-action="Add">Add Animal</a>
                            </li>
                        }
                        <li><a asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a></li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">

            <div class="render-body">

                @if (TempData.ContainsKey(WebConstants.TempDataSuccessMessageKey))
                {
                    <div class="alert alert-success">
                        @TempData[WebConstants.TempDataSuccessMessageKey]
                    </div>
                    <br />
                    <br />
                }

                @if (TempData.ContainsKey(WebConstants.TempDataErrorMessageKey))
                {
                    <div class="alert alert-danger">
                        @TempData[WebConstants.TempDataErrorMessageKey]
                    </div>
                    <br />
                    <br />
                }
                @RenderBody()
            </div>
        </main>
    </div>
    <footer class="border-top footer text-muted" style="padding-top:1%">
        <div class="container">
            &copy; 2019 - Zoo Planet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/bootstrap/dist/js/bootshape.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>